config/routes.rb
Rails.application.routes.draw do
	resources :revenues
	resources :expenses
	resources :categories
	resources :payment_accounts
  resources :assets do
    resources :depreciations
  end

	get '/einstellungen', to: 'settings#index', as: :settings
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :category
  belongs_to :payment_account
  has_many   :depreciations

  DEPRECIATION_YEARS = ['1', '2', '3', '4', '5']

  def self.permitted_params
    %w[item purchase_date amount currency_code payment_date payment_account_id description depreciation category_id]
  end

  def as_blueprint
    blueprint = attributes.slice(*self.class.permitted_params)
    blueprint.merge('transaction_date' => Date.current)
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  def index
    @assets = Asset.all
  end

  def show
    @asset = load_asset
  end

  def new
    @asset = Asset.new(asset_params)
  end

  def create
    @asset = Asset.new(asset_params)
    if @asset.save
      redirect_to @asset, notice: 'Sachanlage wurde gebucht.'
    else
      render :new
    end
  end

  def edit
    load_asset
  end

  def update
    load_asset
    if @asset.update(asset_params)
      redirect_to @asset, notice: 'Sachanlage wurde aktualisiert.'
    else
      render :edit, notice: 'Sachanlage konnte nicht aktualisiert werden.'
    end
  end

  def destroy
    load_asset
    @asset.destroy
    redirect_to assets_path, notice: 'Sachanlage wurde gelöscht'
  end

  private

    def load_asset
      @asset = Asset.find(params[:id])
    end

    def asset_params
      asset_params = params[:asset] || ActionController::Parameters.new
      asset_params.permit(Asset.permitted_params)
    end
end

app/views/assets/_form.html.slim
= form_for(@asset) do |f|

  - if @asset.errors.any?
    = error_messages_for @asset

  .field  
    = f.label :item
    = f.text_field :item, placeholder: 'Labtop'

  .field
    = f.label :purchase_date
    = f.date_field :purchase_date, placeholder: l(Date.current)

  .field
    = f.label :category_id, 'Kategorie'
    = f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Kategorie auswählen'
  
  .field
    = f.label :amount, 'Rechnungsbetrag'
    = f.text_field :amount, placeholder: '1100.25'

  .field 
    = f.label :currency_code, 'Währung'
    = f.collection_select :currency_code, CURRENCY_CODES, :to_s, :to_s, prompt: 'Währung auswählen'

  .field
    = f.label :payment_date, 'Zahlungsdatum'
    = f.date_field :payment_date, placeholder: l(Date.current)

  .field
    = f.label :payment_account_id, 'Zahlung durch'
    = f.collection_select :payment_account_id, PaymentAccount.all, :id, :name, include_blank: 'Zahlungskonto auswählen'

  .field
    = f.label :description, 'Beschreibung'
    = f.text_area :description, rows: 3

    .field
    = f.label :depreciation, 'Anzahl Jahre'
    = f.collection_select :depreciation, Asset::DEPRECIATION_YEARS, :to_s, :to_s, :include_blank => true

  .actions
    = f.submit

app/views/assets/index.html.slim
- provide(:title, 'Ausgaben')

h1
  | Sachanlagen

= link_to icon(:new, 'Neue Sachanlage'), new_asset_path, class: 'btn btn-primary'

hr

ul class="nav nav-tabs"
  = list_item(active_on: assets_path) do
    = link_to 'Sachanlagen', assets_path
  = list_item(active_on: assets_path(archived: true)) do
    = link_to 'Archivierte Sachanlagen', assets_path(archived: true)

- if @assets.empty?
  br
  b 
    | Es gibt noch keine Sachanlagen

- else

  table class="table table-hover table-bordered"
    thead
      tr
        th Artikel
        th Datum
        th Beschreibung
        th Betrag
        th Abschreibungsjahre

    tbody
      - for asset in @assets
        tr
          td = link_to "#{asset.item}", asset
          td = l(asset.payment_date)
          td = asset.description
          td = money_amount('-', asset.amount, asset.currency_code)
          td = asset.depreciation

app/views/assets/new.html.slim
- provide(:title, 'Neue Sachanlage erstellen')
h1
  | Neue Sachanlage erstellen
= render 'form'

app/views/assets/show.html.slim
- provide(:title, 'Sachanlage anzeigen')
h1
  | Sachanlage anzeigen

div = link_to icon(:copy, 'Kopieren'), new_asset_path(asset: @asset.as_blueprint), class: 'btn btn-default'
div = link_to icon(:copy, 'Löschen'), asset_path(@asset), method: :delete, data: { confirm: 'Bist Du sicher, dass Du diese Sachanlage löschen möchtest?' }, class: 'btn btn-default'

= render 'form'