config/routes.rb
Rails.application.routes.draw do
	resources :revenues
	resources :expenses
	resources :categories
	resources :payment_accounts
  resources :assets do
    resources :depreciations
  end

	get '/einstellungen', to: 'settings#index', as: :settings
end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
  include DoesTransaction

  def self.permitted_params
  	%w[invoice_number category_id amount currency_code transaction_date payment_account_id payment_date description]
  end

  def as_blueprint
  	blueprint = attributes.slice(*self.class.permitted_params)
  	blueprint.merge('transaction_date' => Date.current)
  end
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController

  def index
    scope = Revenue.order(:id)
    scope = scope.only_deleted if params[:archived]
    scope = scope.page(params[:page])
    @revenues = scope
  end

  def show
    @revenue = Revenue.find(params[:id])
  end

  def new
    @revenue = Revenue.new(revenue_params)
  end

  def create
    @revenue = Revenue.new(revenue_params)
    if @revenue.save
      redirect_to @revenue, notice: 'Einnahme wurde gebucht.'
    else
      render :new
    end
  end

  def edit
    load_revenue
  end

  def update
    load_revenue
    if @revenue.update(revenue_params)
      redirect_to @revenue, notice: 'Einnahme wurde aktualisiert'
    else
      render :edit
    end
  end

  def destroy
    load_revenue
    @expense.destroy
    redirect_to revenues_path, notice: 'Einnahme wurde gelöscht'
  end

  private

    def load_revenue
      @revenue = Revenue.find(params[:id])
    end

    def revenue_params
      revenue_params = params[:revenue] || ActionController::Parameters.new
      revenue_params.permit(Revenue.permitted_params)
    end

end

app/views/revenues/_form.html.slim
= form_for(@revenue) do |f|

  - if @revenue.errors.any?
    = error_messages_for @revenue

  .field  
    = f.label :invoice_number
    = f.text_field :invoice_number, placeholder: 'Rechnung #123'

  .field
    = f.label :transaction_date
    = f.date_field :transaction_date, placeholder: l(Date.current)

  .field
    = f.label :category_id, 'Kategorie'
    = f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Kategorie auswählen'
  
  .field
    = f.label :amount, 'Rechnungsbetrag'
    = f.text_field :amount, placeholder: '100.25'

  .field 
    = f.label :currency_code, 'Währung'
    = f.collection_select :currency_code, CURRENCY_CODES, :to_s, :to_s, prompt: 'Währung auswaehlen'

  .field
    = f.label :payment_date, 'Zahlungsdatum'
    = f.date_field :payment_date, placeholder: l(Date.current)

  .field
    = f.label :description, 'Beschreibung'
    = f.text_area :description, rows: 3

  .actions
    = f.submit

app/views/revenues/edit.html.slim
- provide(:title, 'Einnahme bearbeiten')
h1
  | Einnahme bearbeiten
= render 'form'

app/views/revenues/index.html.slim
- provide(:title, 'Einnahmens')
h1
  | Einnahme

= link_to icon(:new, 'Neue Einnahme'), new_revenue_path, class: 'btn btn-primary'

ul class="nav nav-tabs"
  = list_item(active_on: revenues_path) do
  	= link_to 'Ausgaben', revenues_path
  = list_item(active_on: revenues_path(archived: true)) do
  	= link_to 'Archivierte Einnahmen', revenues_path(archived: true)

- if @revenues.empty?
	br
	b	
		| Es gibt noch keine Transaktionen

- else

	table class="table table-hover table-bordered"
		thead
			tr
				th No.
				th Datum
				th Beschreibung
				th Betrag

		tbody
			- for revenue in @revenues
				tr
					td = link_to "No. #{revenue.id}", revenue
					td = l(revenue.payment_date)
					td = revenue.description
					td = money_amount('-', revenue.amount, revenue.currency_code)

	ul.pagination
		= will_paginate @expenses, container: false, previous_label: "<", next_label: ">"

app/views/revenues/new.html.slim
- provide(:title, 'Neue Einnahme anlegen')
h1
  | Neue Einnahme anlegen
= render 'form'

app/views/revenues/show.html.slim
- provide(:title, 'Einnahme anzeigen')
h1
  | Einnahme anzeigen

div = link_to icon(:copy, 'Kopieren'), new_expense_path(revenue: @revenue.as_blueprint), class: 'btn btn-default'

= render 'form'