config/routes.rb
Rails.application.routes.draw do
	resources :revenues
	resources :expenses
	resources :categories
	resources :payment_accounts
  resources :assets do
    resources :depreciations
  end

	get '/einstellungen', to: 'settings#index', as: :settings
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :revenues, dependent: :restrict_with_exception
	has_many :expense, dependent: :restrict_with_exception
	validates :name, presence: true

	def destroyable?
		# A category can only be destroyed if no expense is associated
		!Expense.exists?(category_id: id)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		load_category
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to @category, notice: 'Kategorie wurde erstellt.'
    else
      render :edit, alert: "Etwas ging falsch, genau spezifieren was"
		end
	end

	def edit
		load_category
	end

	def update
		load_category
    if @category.update(category_params)
      redirect_to @category, notice: 'Kategorie wurde aktualisiert'
    else
      render :edit, alert: "Etwas ging falsch, genau spezifieren was"
    end
  end

	def destroy
		load_category
		@category.destroy
		redirect_to categories_path, notice: 'Kategorie wurde geloescht.'
	# rescue ActiveRecord::DeleteRestrictionError
	# 	redirect_to @category, alert: "Mit dieser Kategorie sind Ausgaben verbunden. Sie kann daher nicht gelöscht werden."
	end

	private

		def load_category
      @category = Category.find(params[:id])
    end

		def category_params
			params.require(:category).permit(:name, :description)
		end

end

app/views/categories/_form.html.slim
= form_for(@category) do |f|

  - if @category.errors.any?
    = error_messages_for @category

  .field  
    = f.label :name
    = f.text_field :name, placeholder: 'Auto'

  .field
  	= f.label :description
    = f.text_field :description, placeholder: 'Sämtliche Kosten im Zusammenhang mit dem Auto: Benzin, Reparaturen, Autoversicherung, Motorfahrzeugsteuer, Autowäsche usw.'

  .actions
  = f.submit

app/views/categories/edit.html.slim
- provide(:title, 'Kategorie bearbeiten')
h1
  | Kategorie bearbeiten
= render 'form'

app/views/categories/index.html.slim
h1
  | Kategorien

= link_to icon(:new, 'Neue Kategorie'), new_category_path, class: 'btn btn-primary'

- if @categories.empty?

		p Es gibt noch keine Kategorien.

- else

		table class="table table-hover table-bordered"
			thead
  			tr
  				th Name
  				th Beschreibung

			tbody
				- @categories.each do |category|
					tr
						td = link_to "#{category.name}", [:edit, category]
						td = category.description

app/views/categories/new.html.slim
- provide(:title, 'Neue Kategorie anlegen')
h1
  | Neue Kategorie anlegen
= render 'form'

app/views/categories/show.html.slim
- provide(:title, 'Kategorie anzeigen')
h1
  | Kategorie anzeigen

.btn-group
		= link_to "Bearbeiten", [:edit, @category], class: 'btn btn-default'
		- if @category.destroyable? 
			= link_to "Löschen", @category, 
				method: :delete, 
				data: { confirm: "Willst Du die Kategorie wirklich löschen?" }, 
				class: 'btn btn-default'

= render 'form'